### ISSUE TITLE
Move vistools into separate package

### ISSUE THREAD

**Issue by hanslovsky** [hanslovsky/imglyb#10]
This could, possibly, be a separate package, e.g. imglyb_bdv or imglyb_vistools. It is not always necessary (or desired) to have the BDV dependencies on the classpath with imglyb.

Alternatively, this could be controlled through `imglyb_config`.

cc @ctrueden

**Comment by hinerm** [comment]
See also https://github.com/imglib/imglib2-imglyb/issues/9

I think this is an immediate necessity due to the [package change](https://github.com/bigdataviewer/bigdataviewer-core/blob/8887a721bfb2c4a310f9bc27d5c3461b30b0bb2d/src/main/java/bdv/viewer/OverlayRenderer.java#L29) in [OverlayRenderer](https://github.com/imglib/imglyb/blob/0981f26ebd8b39e3a4cb67b9129bcaa12b56a95f/imglyb/util.py#L102)
