### ISSUE TITLE
Python2 compatability? 

### ISSUE THREAD

**Issue by bgriffen** [hanslovsky/imglyb#5]
Would there be a straightforward Python2 work around or is this in conflict with the dependencies. Working on Ubuntu 16.

**Comment by hanslovsky** [comment]
I decided against maintaining compatibility with Python2 because of the [changes to the `import` statement](https://stackoverflow.com/questions/12172791/changes-in-import-statement-python3) that were introduced in Python3 and the [limited lifetime](https://pythonclock.org/) of Python2. If [Python3 on Ubuntu](https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get) is not a solution, I recommend using [conda](conda.io). imglyb is [available on conda](https://github.com/imglib/imglyb#installation) (will migrate from the `hanslovsky` channel to `conda-forge` in the foreseeable future).

**Comment by hanslovsky** [comment]
I will close this issue as Python2 will reach its official end of lifetime by the end of this month.
